(******************************************************************************)
(*                                                                            *)
(*              ARINC 429: Avionics Data Bus Word Format                      *)
(*                                                                            *)
(*     32-bit word encoding with label (octal), SDI, data field, SSM,         *)
(*     and odd parity per ARINC Specification 429. Proves encoding/           *)
(*     decoding roundtrip, parity correctness, and label-space partition.     *)
(*                                                                            *)
(*     "Simplicity is the ultimate sophistication."                           *)
(*     - Leonardo da Vinci                                                    *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: March 16, 2026                                                   *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
